spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/practice_schema
    username: root
    password: 8582
    driver-class-name: com.mysql.cj.jdbc.Driver
