spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://root:dvehr2N5LVJkSU8doGqW@containers-us-west-200.railway.app:6962/railway
    username: root
    password: dvehr2N5LVJkSU8doGqW
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: containers-us-west-134.railway.app
    port: 7928
    password: G5ffGrFuxU85NGaNVAKj
